data:
  image: dylanlindgren/docker-laravel-data
  volumes:
    - .:/data/www/
    - log:/data/logs
  privileged: true

php:
  image: dylanlindgren/docker-laravel-phpfpm
  volumes_from:
    - data
  privileged: true

phpunit:
  image: dylanlindgren/docker-laravel-phpunit
  volumes_from:
    - data

composer:
  image: dylanlindgren/docker-laravel-composer
  volumes_from:
    - data
